mode: rule
external-controller: 127.0.0.1:9090
external-ui: ./metacubexd
allow-lan: false
log-level: warning
ipv6: true
keep-alive-idle: 15
keep-alive-interval: 10
disable-keep-alive: false
unified-delay: false
tcp-concurrent: true
geodata-loader: memconservative
find-process-mode: off
geo-auto-update: true
geo-update-interval: 24
etag-support: true
geodata-mode: true
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
profile:
  store-selected: false
  store-fake-ip: false


tun:
  enable: true
  stack: "gvisor"
  device: "tun0"
  auto-route: true
  auto-detect-interface: true
  strict-route: true


dns:
  enable: true
  cache-algorithm: lru
  listen: 0.0.0.0:1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - geosite:private
  nameserver:
    - tls://1.12.12.12:853
    - tls://223.5.5.5:853


rules:
  - GEOSITE,category-ads-all,REJECT
  - RULE-SET,Advertising_OCD_IP,REJECT,no-resolve

  - DOMAIN-SUFFIX,pages.dev,DIRECT

  - GEOSITE,cn,DIRECT

  - GEOSITE,googlefcm,DIRECT

  - GEOSITE,private,DIRECT
  - GEOIP,private,DIRECT,no-resolve

  - GEOIP,telegram,⚖️负载均衡⚖️,no-resolve
  - GEOSITE,telegram,⚖️负载均衡⚖️
  - GEOSITE,category-cdn-!cn,⚖️负载均衡⚖️
  - GEOSITE,huggingface,⚖️负载均衡⚖️
  - GEOSITE,category-netdisk-!cn,⚖️负载均衡⚖️
  - GEOSITE,python,⚖️负载均衡⚖️
  - GEOSITE,github,⚖️负载均衡⚖️
  - GEOSITE,youtube,⚖️负载均衡⚖️

  - GEOSITE,category-ai-!cn,🧠人工智能🧠

  - GEOSITE,category-cryptocurrency,🪙加密货币🪙

  - MATCH,📌节点选择📌


rule-providers:
  Advertising_OCD_IP:
    type: http
    path: ./rule/Advertising_OCD_IP.mrs
    url: "https://cdn.jsdelivr.net/gh/peiyingyao/Rule-for-OCD@master/rule/Clash/Advertising/Advertising_OCD_IP.mrs"
    interval: 86400
    proxy: DIRECT
    behavior: ipcidr
    format: mrs


proxy-groups:
  - name: 📌节点选择📌
    type: select
    url: https://www.google.com/generate_204
    interval: 600
    timeout: 3000
    max-failed-times: 3
    include-all-proxies: true
    proxies:
      - ⚡自动选择⚡
      - ⚖️负载均衡⚖️
      - 🇯🇵日韩节点🇯🇵
      - 🇭🇰港台节点🇭🇰

  - name: 🧠人工智能🧠
    type: url-test
    url: https://api.openai.com/v1/models
    expected-status: 401
    interval: 600
    timeout: 3000
    max-failed-times: 3
    tolerance: 100
    exclude-filter: 订阅|到期|官网|剩余|RU|俄罗斯|🇷🇺 #|HK|香港|🇭🇰|US|美国|🇺🇸
    include-all-proxies: true
    proxies: []

  - name: 🪙加密货币🪙
    type: url-test
    url: https://api.binance.com/api/v3/ping
    expected-status: 200
    interval: 600
    timeout: 3000
    max-failed-times: 3
    tolerance: 100
    exclude-filter: 订阅|到期|官网|剩余|RU|俄罗斯|🇷🇺|CA|加拿大|🇨🇦|US|美国|🇺🇸
    include-all-proxies: true
    proxies: []

  - name: ⚡自动选择⚡
    type: url-test
    url: https://www.google.com/generate_204
    interval: 600
    timeout: 3000
    max-failed-times: 3
    tolerance: 100
    exclude-filter: 订阅|到期|官网|剩余|RU|俄罗斯|🇷🇺|KR|韩国|🇰🇷
    include-all-proxies: true
    proxies: [ ]

  - name: 🇯🇵日韩节点🇯🇵
    type: url-test
    url: https://www.dlsite.com
    interval: 600
    timeout: 3000
    max-failed-times: 3
    tolerance: 100
    filter: JP|日本|🇯🇵|KR|韩国|🇰🇷
    include-all-proxies: true
    proxies: [ ]

  - name: 🇭🇰港台节点🇭🇰
    type: url-test
    url: https://www.google.com/generate_204
    interval: 600
    timeout: 3000
    max-failed-times: 3
    tolerance: 100
    filter: HK|香港|🇭🇰|TW|台湾|🇹🇼
    include-all-proxies: true
    proxies: [ ]

  - name: ⚖️负载均衡⚖️
    type: load-balance
    strategy: consistent-hashing
    url: https://web.telegram.org/k
    interval: 600
    timeout: 3000
    max-failed-times: 3
    tolerance: 100
    exclude-filter: 订阅|到期|官网|剩余|RU|俄罗斯|🇷🇺|KR|韩国|🇰🇷  #|VN|越南|🇻🇳|MY|马来西亚|🇲🇾|🇷🇺
    include-all-proxies: true
    proxies: []